finished basic features

diff --git a/location b/location
--- a/location
+++ b/location
@@ -1,23 +1,92 @@
 #!/bin/sh
-# `location` gets where you are.
-# for Mac OS X ONLY
+# `location` gets where you are, returns Markdown.
+# <3 for OS X ONLY currently
 # by @leaskh
 
 # Requirement
 # `brew install whereami`
 # `brew install jq`
 
-coordinate=`whereami`
-locationJson="http://maps.google.com/maps/api/geocode/json?latlng=${coordinate}&language=en-US&sensor=true"
-locationGMap="https://www.google.com/maps/place/${coordinate}"
-locations=`proxychains4 curl -s "$locationJson"`
-curLocation=`echo $locations | jq -r '.results[0].formatted_address'`
-if [ "$curLocation" = 'null' ]; then
-    curLocation=''
-fi
-echo $curLocation;
+init() {
+    coordinate=`whereami`
+    if [ "$coordinate" = '' ]; then
+        echo 'Error getting coordinate, please retry later.'
+        exit 1
+    fi
+    locationJson="https://maps.google.com/maps/api/geocode/json?latlng=${coordinate}&language=en-US&sensor=true"
+    locationGMap="https://www.google.com/maps/place/${coordinate}"
+    locationImgL="https://maps.googleapis.com/maps/api/staticmap?center=${coordinate}&zoom=13&size=640x480&scale=2&markers=|${coordinate}"
+    locations=`curl -s "$locationJson"`
+    # locations=`proxychains4 curl -s "$locationJson"`
+    curLocation=`echo $locations | jq -r '.results[0].formatted_address'`
+}
 
+markLink() {
+    echo "[${1}](${2} \"${3}\")"
+}
 
+markImage() {
+    echo "![${1}](${2} \"${3}\")"
+}
 
+locationLink() {
+    init
+    if [ "$curLocation" = 'null' ]; then
+        text=$coordinate
+    else
+        text=$curLocation
+    fi
+    echo `markLink "$text" "$locationGMap" "$coordinate"`
+}
 
-# URL="http://maps.google.com/maps?q=${LAT},${LON}($(hostname),+${MYIP},+$(echo $ERR | urlencode),+$(date | urlencode))&ie=UTF8&ll=${LAT},${LON}&t=roadmap&z=14&iwloc=A&mrt=loc"
+locationImage() {
+    init
+    if [ "$curLocation" = 'null' ]; then
+        text=$coordinate
+    else
+        text=$curLocation
+    fi
+    echo `markImage "$text" "$locationImgL" "$coordinate"`
+}
+
+locationImglnk() {
+    init
+    if [ "$curLocation" = 'null' ]; then
+        text="`locationImage` $coordinate"
+    else
+        text="`locationImage` $curLocation"
+    fi
+    echo `markLink "$text"  "$locationImgL" "$coordinate"`
+}
+
+showHelp() {
+    echo '`location` gets where you are, returns Markdown.'
+    echo '================================================'
+    echo '<3 for OS X ONLY currently'
+    echo ''
+    echo '- link   : Make Markdown location link block'
+    echo '- image  : Make Markdown location image block'
+    echo '- imglnk : Make Markdown location link block with image'
+    echo '- help   : Show this infos'
+}
+
+unknowCommand() {
+    showHelp
+    exit 1
+}
+
+# Main logic
+coordinate=''
+locationJson=''
+locationGMap=''
+locationImgL=''
+locations=''
+curLocation=''
+case "$1" in
+    'link'  ) locationLink  ;;
+    'image' ) locationImage ;;
+    'imglnk') locationImglnk;;
+    'help'  ) showHelp      ;;
+    *       ) unknowCommand ;;
+esac
+exit 0
